coachme/coachme/urls.py
from django.contrib import admin
from django.urls import include, path

from schedules import views

urlpatterns = [
    path('', views.Schedule.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('schedule/', include('schedules.urls', namespace='schedule')),
    path('users/', include('users.urls', namespace='users')),
]

coachme/schedules/urls.py
from django.contrib import admin
from django.urls import include, path

from .views import Schedule

app_name = 'schedule'

urlpatterns = [
    path('delete/<int:pk>/', Schedule.as_view(), { 'delete': True }, name='delete'),
    path('<slug:username>/', Schedule.as_view(), name='coach'),
    path('', Schedule.as_view(), name='user'),
]

coachme/users/urls.py
from django.contrib import admin
from django.urls import include, path

from .views import Login, Logout

app_name = 'users'

urlpatterns = [
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
]

coachme/ess/models/fields.py
from django import forms
from django.db import models

from ess.utils import format_phone

class PhoneField(models.CharField):
    """Поле для хранения телефонного номера."""

    def __init__(self, *args, **kwargs):
        kwargs["max_length"] = 10
        super().__init__(*args, **kwargs)

    def to_python(self, value):
        return format_phone(value)

    def formfield(self, **kwargs):
        return super().formfield(max_length=20, **kwargs)


class MultiLineCharField(models.CharField):
    """Поле для коротких многострочных текстовых данных."""

    def formfield(self, **kwargs):
        kwargs["widget"] = forms.Textarea
        return super().formfield(**kwargs)


class TimeField(models.TimeField):
    """Поле для указания времени в формате XX:XX."""

    def formfield(self, **kwargs):
        kwargs["widget"] = forms.TimeInput(attrs={"type":"time","size":5})
        return super().formfield(**kwargs)

coachme/schedules/models.py
from django.db import models

# Create your models here.

coachme/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.functional import cached_property

from ess.models.fields import PhoneField

class User(AbstractUser):
    email = models.EmailField("E-mail", unique=True)
    phone = PhoneField("Телефон", blank=True)

    class Meta:
        db_table = "users"
        verbose_name = "пользователь"
        verbose_name_plural = "пользователи"

    def __str__(self):
        return self.username

    # @cached_property
    # def cities(self):
    #     return self.city.only("pk", "title", "label")

    # @cached_property
    # def cities_index(self):
    #     return tuple(self.cities.values_list("pk", flat=True))

    # @cached_property
    # def has_multi_city(self):
    #     return len(self.cities_index) > 1

    # def city_filter(self, queryset):
    #     # if self.is_superuser:
    #     #     return queryset
    #     return queryset.filter(city__in=self.cities_index)

coachme/schedules/views.py
from django.shortcuts import render, get_object_or_404
from django.views import View
from django.views.generic.base import TemplateResponseMixin

class Schedule(TemplateResponseMixin, View):
    template_name = 'index.html'

    def dispatch(self, request, *args, **kwargs):
        if kwargs.get('delete', False):
            return self.delete(request, *args, **kwargs)
        return super().dispatch(request, *args, **kwargs)
 
    def get(self, request, *args, username=None):
        '''Отображание главной страницы'''
        context = {"username": username}
        
        return self.render_to_response(context)
    
    def delete(self, request, *args, **kwargs):
        return self.render_to_response({"username":"delete"})

coachme/users/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy
from django.contrib import messages


class Login(LoginView):
    template_name = 'users/login.html'
    redirect_authenticated_user = True
    
    def get_success_url(self):
        return reverse_lazy('schedule:user') 
    
    def form_invalid(self, form):
        messages.error(self.request,'Invalid username or password')
        return self.render_to_response(self.get_context_data(form=form))
    

class Logout(LogoutView):
    next_page = 'index'

coachme/templates/index.html
<html>
<head>
    <title>Coach ME</title>
</head>
<body>
    <div class='root__menu'>
        {% block root_menu %}
        {% if request.user.is_authenticated %}
            <form method="post" action="{% url 'users:logout' %}">
                {% csrf_token %}
                <input type="submit" value="Выход">
            </form>
        {% else %}
            Вход
        {% endif %}
        {% endblock %}
    </div>
    <div>
        {% block content %}
            {{ username }}
        {% endblock %}
    </div>
</body>
</html>

coachme/templates/users/login.html
{% extends "index.html" %}

{% block content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'users:login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login">
<input type="hidden" name="next" value="{{ next }}">
</form>

{% endblock %}